### ISSUE TITLE
为什么这样预览出来的是空的呢

### ISSUE THREAD

**Issue by wfxt0911** [Dark2017/vue-dark-photo#5]
<VDPhoto ref="VDPhoto" imgData='https://picsum.photos/300/200'  /> 为什么这样预览出来的是空的呢

**Comment by wfxt0911** [comment]
<VDPhoto ref="VDPhoto" imgData='https://picsum.photos/300/200'  />

**Comment by wfxt0911** [comment]
VDPhoto ref="VDPhoto" imgData='https://picsum.photos/300/200'

**Comment by Dark2017** [comment]
有图或者具体代码看一下吗

**Comment by Dark2017** [comment]
已解决，请安装最新包
